<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>404 HTML Template by Colorlib</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Cabin:400,700" rel="stylesheet">

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="assets/css/error-page.css" />


</head>

<body>

    <div id="notfound">
        <div class="notfound">
            <div class="notfound-404">
                <div></div>
                <h1>404</h1>
            </div>
            <h2>Página não encontrada</h2>
            <p>A página que você está procurando pode ter sido removida, teve seu nome alterado ou está temporariamente indisponível.</p>

            <?php

            use App\Controllers\AuthController;

            if (AuthController::esta_logado()) {
            ?>
                <a href="/admin">voltar ao site</a>
            <?php
            } else {
            ?>
                <a href="/">voltar ao site</a>
            <?php
            }
            ?>

        </div>
    </div>

</body>

</html>