<head>
    <link rel="stylesheet" href="assets/css/cardapio/style.css">
</head>

<section class="cardapio" id="cardapio">
    <div class="card__cardapio">
        <button class="favoritado"></button>
        <img src="assets/img/cardapio/hamburguer.png" alt="produto" class="img__card">
        <h3 class="nome__card">Hamburguer</h3>
        <p class="desc__card">
            Salgado de hamburguer(bovino), presunto e catupiry.
        </p>
        <div class="acoes__card">
            <h2 class="preco__card">
                R$7,00
            </h2>
            <button class="add__carrinho"></button>
        </div>
    </div>
</section>