<head>
    <link rel="stylesheet" href="assets/css/reservas/style.css">
</head>

<table class="tabela">
    <thead>
        <tr>
            <td>Produtos</td>
            <td>Data programada</td>
            <td>Valor</td>
            <td>Token</td>
        </tr>
    </thead>
    <tbody>
        <?php
        $reservas = $this->view->reservas;
        $produtos = $this->view->produtos;


        foreach ($reservas as $reserva) {
            foreach ($produtos as $produto) {
                if ($reserva['id_usuarios'] == $_SESSION['id']) {
                    echo "<tr class='item__tabela'>";
                    echo "<td>{$produto['nome_produto']}</td>";
                    echo "<td class='data'>{$reserva['data_formatada']}</td>";
                    echo "<td>R$ {$reserva['valor_produto']}</td>";
                    echo "<td></td>";
                    echo "</tr>";
                }
            }
        }
        ?>
    </tbody>
</table>