<head>
    <link rel="stylesheet" href="assets/css/pagamento/style.css">
</head>

<section class="pagamento">
    <div class="campos">
        <div class="header__campos">
            <h2>Pagamento</h2>
            <select name="metodo" id="metodo">
                <option value="pix">Pix</option>
                <option value="credito">Crédito</option>
                <option value="debito">Débito</option>
            </select>
        </div>
        <form method="post" id="form" class="corpo">
            <label class="campo" for="data">
                Data de retirada:
                <input name="data" class="campo__input" type="date">
            </label>
            <button>Comprar</button>
        </form>
    </div>

</section>

<script>
    const metodo = document.querySelector('#metodo')
</script>