<!doctype html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cantina Senai</title>
    <link rel="stylesheet" href="assets/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>

<body>

    <header class="cabecalho">
        <div class="info__header">
            <a href="#" class="logo__header"> Cantina Senai</a>
            <div class="funcoes__header">
                <a href="../cardapio/index.phtml" class="item__nav">Cardápio</a>
                <a href="#" class="item__nav">Ouvidoria</a>
                <a href="#" class="item__nav">Sobre</a>
                <button class="funcao__item btn__favoritos"></button>
                <button class="funcao__item btn__carrinho"></button>
                <a href="../login/index.phtml" class="btn__login">Login</a>
            </div>
        </div>
    </header>

    <main class="corpo">

    </main>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>

</html>