<?php


use \vendor\MercadoPago\Payer;

  MercadoPago\SDK::setAccessToken("ENV_ACCESS_TOKEN");

  $payment = new MercadoPago\Payment();

  $payment->transaction_amount = 100;
  $payment->token = "ff8080814c11e237014c1ff593b57b4d";
  $payment->installments = 1;
  $payment->payer = array(
        "type" => "customer",
        "id" => "123456789-jxOV430go9fx2e",
        "email" => "Payer@gmail.com"
    ); 

  $payment->save();

  $copia_e_cola =  $payment->point_or_interaction->transaction_data->qr_code;

  echo $copia_e_cola;
  die;

  echo '<pre>';
  var_dump($payment)
  
  ?>
      