<head>
    <link rel="stylesheet" href="assets/css/admin/adicionar/style.css">
</head>


<section class="sistema">
    <h1 class="titulo__sistema">
        Adicionar produtos
    </h1>
    <form class="form__add">
        <div class="campo__input">
            <label for="categoria" class="label__input">Digite a categoria do produto:</label>
            <select name="categoria" class="input__form">
                <option value="" disabled selected></option>
                <option value="salgado">Salgado</option>
                <option value="bebida">Bebida</option>
                <option value="sobremesa">Sobremesa</option>
            </select>
        </div>
        <div class="campo__input">
            <label for="nome" class="label__input">Digite o nome do produto:</label>
            <input type="text" name="nome" class="input__form">
        </div>
        <div class="campo__input">
            <label for="nome" class="label__input">Digite a descrição do produto:</label>
            <textarea type="text" name="nome" class="input__form"></textarea>
        </div>
        <div class="campo__input">
            <label for="custo" class="label__input">Digite o custo do produto:</label>
            <input type="number" name="custo" class="input__form">
        </div>
        <div class="campo__input">
            <label for="valor" class="label__input">Digite o valor do produto:</label>
            <input type="number" name="valor" class="input__form">
        </div>
        <div class="campo__input">
            <label for="qtd" class="label__input">Digite a quantidade do produto:</label>
            <input type="number" name="qtd" class="input__form">
        </div>
        <div></div>
        <button type="submit" class="btn__add">Adicionar Produto</button>
    </form>
</section>