<head>
    <link rel="stylesheet" href="assets/css/admin/detalhes/style.css">
</head>

<section class="sistema">
    <h1 class="titulo__sistema">Detalhes do pedido</h1>
    <div class="info">
        <h5>Nome do cliente :</h5>
        <h5> INFORMAÇÃO</h5>
    </div>
    <div class="info">
        <h5> Email do cliente :</h5>
        <h5> INFORMAÇÃO</h5>
    </div>
    <div class="info">
        <h5>Nome do produto :</h5>
        <h5> INFORMAÇÃO</h5>
    </div>
    <div class="info">
        <h5>Descrição do produto :</h5>
        <h5> INFORMAÇÃO</h5>
    </div>
    <div class="info">
        <h5>Categoria :</h5>
        <h5> INFORMAÇÃO</h5>
    </div>
    <div class="info">
        <h5>Quantidade :</h5>
        <h5> INFORMAÇÃO</h5>
    </div>
    <div class="info">
        <h5>Valor :</h5>
        <h5> INFORMAÇÃO</h5>
    </div>
    <div class="info">
        <h5>Data de Retirada :</h5>
        <h5> INFORMAÇÃO</h5>
    </div>
    <div class="info">
        <h5>Token :</h5>
        <h5> INFORMAÇÃO</h5>
    </div>
</section>