<head>
    <link rel="stylesheet" href="assets/css/admin/lista/style.css">
</head>

<section class="sistema">
    <h1 class="titulo__sistema">
        Tabela de produtos
    </h1>
    <input type="text" class="filtro__lista" placeholder="Buscar produto...">
    <img src="assets/img/lupa.png" width="30rem" style="margin-left: -3rem;" alt="">
    <table class="tabela">
        <thead class="header__tabela">
            <th>Categoria</th>
            <th>Produto</th>
            <th>Descrição</th>
            <th>Quantidade</th>
            <th>Valor</th>
            <th>Custo</th>
            <th>Status</th>
            <th>Editar</th>
        </thead>
        <tbody class="corpo__tabela">

        <?php
            $produtos = $this->view->produtos;

            foreach($produtos as $produto){
                echo "<tr class='linha__tabela'>
                <td class='item__tabela'>{$produto['categoria']}</td>
                <td class='item__tabela'>{$produto['nome_produto']}</td>
                <td class='item__tabela'>{$produto['descricao']}</td>
                <td class='item__tabela'>{$produto['quantidade_produto']}</td>
                <td class='item__tabela'>{$produto['valor']}</td>
                <td class='item__tabela'>{$produto['custo']}</td>
                <td class='item__tabela item__status'>Ativo</td>
                <td class='item__tabela'>
                   <a href='/editarProduto'><button class='btn btn-warning'>Editar</button></a>
                   <a href='/excluirProduto'><button class='btn btn__excluir btn-danger '>Excluir</button></a>
                </td>
            </tr>";
            }
        ?>


            
        </tbody>
    </table>
</section>