<head>
    <link rel="stylesheet" href="assets/css/admin/lista/style.css">
</head>

<section class="sistema">
    <h1 class="titulo__sistema">
        Tabela de produtos
    </h1>
    <input type="text" class="filtro__lista" placeholder="Buscar produto...">
    <img src="assets/img/lupa.png" width="30rem" style="margin-left: -3rem;" alt="">
    <table class="tabela">
        <thead class="header__tabela">
            <th>Categoria</th>
            <th>Produto</th>
            <th>Descrição</th>
            <th>Quantidade</th>
            <th>Valor</th>
            <th>Custo</th>
            <th>Status</th>
            <th>Editar</th>
        </thead>
        <tbody class="corpo__tabela">
            <tr class="linha__tabela">
                <td class="item__tabela">Salgado</td>
                <td class="item__tabela">Coxinha</td>
                <td class="item__tabela">Masse de mandioca, recheio de frango</td>
                <td class="item__tabela">500</td>
                <td class="item__tabela">7,00</td>
                <td class="item__tabela">3,00</td>
                <td class="item__tabela item__status">Ativo</td>
                <td class="item__tabela">
                    <button class="btn btn-warning">Editar</button>
                    <button class="btn btn__excluir btn-danger ">Excluir</button>
                </td>
            </tr>
            <tr class="linha__tabela">
                <td class="item__tabela">Salgado</td>
                <td class="item__tabela">Coxinha</td>
                <td class="item__tabela">Masse de mandioca, recheio de frango</td>
                <td class="item__tabela">500</td>
                <td class="item__tabela">7,00</td>
                <td class="item__tabela">3,00</td>
                <td class="item__tabela item__status">Ativo</td>
                <td class="item__tabela">
                    <button class="btn btn-warning">Editar</button>
                    <button class="btn btn__excluir btn-danger ">Excluir</button>
                </td>
            </tr>
            <tr class="linha__tabela">
                <td class="item__tabela">Salgado</td>
                <td class="item__tabela">Coxinha</td>
                <td class="item__tabela">Masse de mandioca, recheio de frango</td>
                <td class="item__tabela">500</td>
                <td class="item__tabela">7,00</td>
                <td class="item__tabela">3,00</td>
                <td class="item__tabela item__status">Ativo</td>
                <td class="item__tabela">
                    <button class="btn btn-warning">Editar</button>
                    <button class="btn btn__excluir btn-danger ">Excluir</button>
                </td>
            </tr>
            <tr class="linha__tabela">
                <td class="item__tabela">Salgado</td>
                <td class="item__tabela">Coxinha</td>
                <td class="item__tabela">Masse de mandioca, recheio de frango</td>
                <td class="item__tabela">500</td>
                <td class="item__tabela">7,00</td>
                <td class="item__tabela">3,00</td>
                <td class="item__tabela item__status">Ativo</td>
                <td class="item__tabela">
                    <button class="btn btn-warning">Editar</button>
                    <button class="btn btn__excluir btn-danger ">Excluir</button>
                </td>
            </tr>
        </tbody>
    </table>
</section>