<head>
    <link rel="stylesheet" href="assets/css/admin/lista/style.css">
</head>

<section class="sistema">
    <h1 class="titulo__sistema">
        Tabela de reservas
    </h1>
    <input type="text" class="filtro__lista" placeholder="Buscar produto...">
    <img src="assets/img/lupa.png" width="30rem" style="margin-left: -3rem;" alt="">
    <table class="tabela">
        <thead class="header__tabela">
            <th>Email Reservante</th>
            <th>Produto</th>
            <th>Descrição</th>
            <th>Quantidade</th>
            <th>Valor</th>
            <th>Data</th>
            <th></th>
        </thead>
        <tbody class="corpo__tabela">
            <?php
            $reservas = $this->view->reservas;

            foreach ($reservas as $reserva) {
                echo "<tr>
                    <td>{$reserva['email']}</td>
                    </tr>";
            }
            ?>
        </tbody>
    </table>
</section>