<head>
    <link rel='stylesheet' href='assets/css/admin/lista/style.css'>
</head>
<section class='sistema'>
    <h1 class='titulo__sistema'>
        Tabela de reservas
    </h1>
    <input type='text' class='filtro__lista' placeholder='Buscar produto...'>
    <img src='assets/img/lupa.png' width='30rem' style='margin-left: -3rem;' alt=''>
    <table class='tabela'>
        <thead class='header__tabela'>
            <th>Email Reservante</th>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Valor</th>
            <th>Data</th>
            <th>Token</th>
            <th>Ações</th>
        </thead>
        <tbody class='corpo__tabela'>
             <?php
            $reservas = $this->view->reservas;

            foreach ($reservas as $reserva) {
                echo "<tr>
                <td class='item__tabela'>{$reserva['email_usuario']}</td>
                <td class='item__tabela'>{$reserva['quantidade']}</td>
                <td class='item__tabela'>{$reserva['valor_produto']}</td>
                <td class='item__tabela'>{$reserva['data_formatada']}</td>
                <td class='item__tabela'>1234567890</td>
               
                <td class='item__tabela'>
                    <a href='/detalhesReserva?reserva=" . $reserva['id'] . "'>
                        <button class='btn btn-warning'>
                            <svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-eye' viewBox='0 0 16 16'>
                                <path d='M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z' />
                                <path d='M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z' />
                            </svg></button></a>

                    <a href='/deletarReserva?id=" . $reserva['id'] . "'><button class='btn btn-danger'>
                            <svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-x-lg' viewBox='0 0 16 16'>
                                <path d='M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z' />
                            </svg></button></a>
                </td>
            </tr>";
            }
            ?>
        </tbody>
    </table>
</section>