<div><h1></h1></div>
<center><div class="container"><h5>Bem-vindo à nossa página sobre a Cantina Escolar! Aqui, mergulhamos no 
delicioso universo de nossas opções de salgados que certamente conquistarão 
seu paladar. Desde saborosos pastéis até irresistíveis empadas, nossa cantina
é um ponto de encontro para os amantes de uma boa comida escolar. Explore nossa 
variedade de produtos frescos e preparados com cuidado para oferecer uma experiência
 gastronômica única. Saiba mais sobre as vendas diárias e descubra por que somos o 
destino preferido para uma pausa saborosa durante o dia letivo.</h5></div></center>