<!doctype html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cantina Senai</title>
    <link rel="stylesheet" href="assets/css/layout/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    
</head>

<body>

    <header class="cabecalho">
        <div class="info__header">
            <a href="#" class="logo__header">Cantina Senai</a>
            <div class="funcoes__header">
                <a href="/favoritos" class="funcao__item btn__favoritos"></a>
                <a href="/carrinho" class="funcao__item btn__carrinho"></a>
                <?php

                use App\controllers\AuthController;

                if (AuthController::esta_logado()) {
                    if ($_SESSION['nivel'] == 1) {
                        echo "<a href='/adminLista'class='btn__login'>Admin</a>";
                    } else {
                        echo "<a href='/sair' class='btn__login'>Sair</a>";
                    }
                } else {
                    echo "<a href='/login' class='btn__login'>Login</a>";
                }
                ?>

            </div>
        </div>
        <nav class="nav__header">
            <a href="/" class="item__nav">Cardápio</a>
            <a href="/ouvidoria" class="item__nav">Ouvidoria</a>
            <a href="/sobre" class="item__nav">Sobre</a>
        </nav>
    </header>

    <main class="corpo">
        <?= $this->content(); ?>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>

</html>