<!doctype html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cantina Senai</title>
    <link rel="stylesheet" href="assets/css/admin/layout/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
 
</head>

<body>
    <nav class="nav__admin">
        <h1 class="titulo__nav">Cantina</h1>
        <h2 class="subtitulo__nav">SISTEMA DE GERENCIAMENTO</h2>
        <div class="itens__nav">
            <img class="icons" src="admin/assets/img/tabela.png" width="65%">
            <a href="/adminLista" class="item__nav">Tabela produtos</a>
            <img class="icons" src="admin/assets/img/add.png" width="70%">
            <a href="/adminAdicionar" class="item__nav">Adicionar produtos</a>
            <img class="icons" src="admin/assets/img/add.png" width="70%">
            <a href="/adminReservas" class="item__nav">Reservas</a>
            <img class="icons" src="admin/assets/img/add.png" width="70%">
            <a href="/" class="item__nav">Cardápio</a>
        </div>
        <div class="logout">
            <h2 class="mensagem">Oi, Lúcia</h2>
            <a href="/sair" class="btn__logout">Sair</a>
        </div>
    </nav>

    <main class="corpo">
        <?= $this->content(); ?>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>

</html>